### ISSUE TITLE
feature request: mouse operations

### ISSUE THREAD

**Issue by ghost** [fuzzykiller/resizeit2#1]
A simple drop-down menu ( 4 lines - sizes, plus the link to options) to operate with just a mouse, because keyboard often isn't accessible (a beer in a left hand to be honest:)
Thanks anyway.

**Comment by btzdnl** [comment]
I had hoped to avoid that, but oh well. Still, the earliest I can work on this is in two weeks.

**Comment by btzdnl** [comment]
Fixed in a4e5812fe41396ab2c113ee69c2f50cbca1a3356, (soon) available on AMO as version 1.2.0.
