### ISSUE TITLE
Default size at startup

### ISSUE THREAD

**Issue by mailueberfalln** [fuzzykiller/resizeit2#10]
A 2nd browser window does not get default size!

**Comment by btzdnl** [comment]
You’re right, startup means startup. I’ll add an option to apply the startup setting to new windows as well.

**Comment by mailueberfalln** [comment]
Hello, why do you want to differ 1st, 2nd or 3rd window, why not start all in same size?

**Comment by btzdnl** [comment]
I do not. The browser starting and new windows opening are independent events. The extension currently deals only with the former. With the new feature it will _optionally_ also handle the latter. That’s what I’m saying above. I will not change the current behavior. I will add new behavior.

**Comment by btzdnl** [comment]
Thank you for your patience. The update is now available on [AMO](https://addons.mozilla.org).
