### ISSUE TITLE
Firefox switches tabs on ALT + 1/2/3/4

### ISSUE THREAD

**Issue by hugopeek** [fuzzykiller/resizeit2#2]
Observed in FF 59 and dev edition, on Linux.

CTRL + 1/2/3/4 doesn't seem to do anything btw.. So maybe that can be used for all versions?

**Comment by btzdnl** [comment]
Seems to be a Linux thing. I’ll change the shortcut key for Linux to <kbd>Ctrl</kbd>, then. On Windows, <kbd>Ctrl</kbd>+<kbd>1</kbd> etc switches tabs.

In the future (tm), all this will be user-configurable: https://bugzilla.mozilla.org/show_bug.cgi?id=1303384

**Comment by btzdnl** [comment]
Fixed in efb51bc474354881c0a6cbc0fce5fd5c2c59e7ad, (soon) available on AMO as version 1.2.0.
